import type { ActiveTestSnapshotV2, CapabilitySection, DiagnosticSnapshot, SignalEvidence, SignalSnapshot } from "./types";

type MockSignalComposition = SignalSnapshot["composition"];
type MockSignalSnapshot = SignalSnapshot;
type MockCapabilitySection = CapabilitySection;

type MockDiagnosticSnapshot = DiagnosticSnapshot & {
  capability_sections: MockCapabilitySection[];
  signals: MockSignalSnapshot[];
  active_tests_v2: ActiveTestSnapshotV2[];
  diagnostic_services: Array<{
    key: string;
    label: string;
    module: string;
    state: string;
    detail: string;
  }>;
};

function signal(
  key: string,
  label: string,
  category: MockSignalSnapshot["category"],
  unit: string,
  value: number | null,
  composition: MockSignalComposition,
  options: Partial<Pick<MockSignalSnapshot, "confidence" | "state" | "provenance" | "evidence_policy" | "failure_policy" | "preferred_over" | "module" | "evidence">> = {},
): MockSignalSnapshot {
  return {
    key,
    label,
    category,
    unit,
    value,
    state: options.state ?? "ok",
    confidence: options.confidence ?? "Verified",
    provenance: options.provenance ?? ["mock profile"],
    source_fields: null,
    request: options.evidence?.request ?? null,
    decoder_id: null,
    evidence_policy: options.evidence_policy ?? "normal",
    failure_policy: options.failure_policy ?? "retain",
    preferred_over: options.preferred_over ?? null,
    module: options.module ?? "ECM",
    evidence: options.evidence ?? null,
    composition,
  };
}

const fuelRailActualEvidence: SignalEvidence = {
  key: "fuel_rail_actual",
  label: "Actual fuel rail SAE PID 01 23",
  module: "ECM",
  node: "broadcast",
  request: "01 23",
  source: "SAE standard PID",
  confidence: "standard; forced direct poll",
  status: "success",
  unit: "psi",
  value: 4260,
  response: null,
  notes: "Full-range gauge pressure; preferred over GM $22 163E X-Gauge scaling.",
};

const fuelRailActualGmEvidence: SignalEvidence = {
  key: "fuel_rail_actual_gm",
  label: "Actual fuel rail GM $22 163E 01",
  module: "ECM/PCM",
  node: "0x10",
  request: "6C 10 F1 22 16 3E 01",
  source: "GM Mode 22",
  confidence: "ScanGauge published + live-observed; range-suspect",
  status: "success",
  unit: "psi",
  value: 4248,
  response: "1D4C",
  notes: "Standard PID 01 23 remains preferred for the displayed actual rail pressure.",
};

const fuelRailDesiredEvidence: SignalEvidence = {
  key: "fuel_rail_desired",
  label: "Desired fuel rail GM $22 163D 01",
  module: "ECM/PCM",
  node: "0x10",
  request: "6C 10 F1 22 16 3D 01",
  source: "GM Mode 22",
  confidence: "ScanGauge published + live-observed; range-suspect",
  status: "success",
  unit: "psi",
  value: 5510,
  response: "2600",
  notes: "Display scaling is retained from current live/probe code until persisted bytes are cross-checked.",
};

const desiredMapEvidence: SignalEvidence = {
  key: "desired_map",
  label: "Desired MAP GM $22 1542 01 candidate",
  module: "ECM/PCM",
  node: "0x10",
  request: "6C 10 F1 22 15 42 01",
  source: "GM Mode 22",
  confidence: "candidate; live behavior observed, validation pending",
  status: "success",
  unit: "kPa abs",
  value: 103,
  response: "67",
  notes: "Display as absolute pressure until cross-checked against a factory-equivalent tool.",
};

const barometerEvidence: SignalEvidence = {
  key: "barometric_pressure_gm",
  label: "Barometer GM $22 1251 01 candidate",
  module: "ECM/PCM",
  node: "0x10",
  request: "6C 10 F1 22 12 51 01",
  source: "GM Mode 22",
  confidence: "candidate/live-observed; persisted byte evidence pending",
  status: "success",
  unit: "kPa abs",
  value: 95,
  response: "5F",
  notes: "Used when standard PID 01 33 is unavailable or stale.",
};

const sourceConfidence = [
  fuelRailActualEvidence,
  fuelRailActualGmEvidence,
  fuelRailDesiredEvidence,
  desiredMapEvidence,
  barometerEvidence,
];

export const fallbackSnapshot: MockDiagnosticSnapshot = {
  mode: { state: "telemetry" },
  capability_state: { persistence: "cached", verification: "ready", remaining: null },
  foreground_result: null,
  vehicle: "2004 GMC Sierra",
  vin: "1GTHK29294E391526",
  vin_source: "observed",
  protocol: "J1850 VPW",
  connection: "browser mock",
  connection_state: "live",
  telemetry_fresh: true,
  voltage: 13.8,
  rpm: 685,
  speed_mph: 0,
  poll_ms: 250,
  units: "US",
  statuses: [
    { label: "DTCs", value: "0", state: "ok" },
    { label: "ECUs", value: "5", state: "ok" },
    { label: "MIL", value: "OFF", state: "ok" },
    { label: "Record", value: "armed", state: "warn" },
  ],
  capability_sections: [
    {
      id: "powertrain",
      category: "Powertrain",
      label: "Powertrain",
      signal_keys: ["map_absolute", "maf", "boost"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "turbo",
      category: "Turbo",
      label: "Turbo",
      signal_keys: ["vgt_actual", "vgt_desired", "vgt_error"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "fuel",
      category: "Fuel",
      label: "Fuel",
      signal_keys: [
        "fuel_rail_actual",
        "fuel_rail_desired",
        "fuel_rail_delta",
        "injector_balance_1",
        "injector_balance_2",
        "injector_balance_3",
        "injector_balance_4",
        "injector_balance_5",
        "injector_balance_6",
        "injector_balance_7",
        "injector_balance_8",
      ],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "other",
      category: "Other",
      label: "Other",
      signal_keys: ["coolant_temp", "intake_air_temp", "oil_temp", "trans_temp", "ambient_temp", "battery_voltage"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "discovery",
      category: "Discovery",
      label: "Discovery",
      signal_keys: ["desired_map", "barometer"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "diagnostics",
      category: "Diagnostics",
      label: "Diagnostics",
      signal_keys: [],
      active_test_keys: [],
      diagnostic_service_keys: ["sae_dtc", "gm_class2_19"],
      visible: true,
    },
    {
      id: "active-tests",
      category: "ActiveTests",
      label: "Active Tests",
      signal_keys: [],
      active_test_keys: ["turbo_vane_control"],
      diagnostic_service_keys: [],
      visible: true,
    },
  ],
  signals: [
    signal("map_absolute", "Intake MAP", "Powertrain", "psi", 13.9, { kind: "scalar" }),
    signal("maf", "MAF", "Powertrain", "g/s", 39.0, { kind: "scalar" }),
    signal("boost", "Boost", "Powertrain", "psi", 0, {
      kind: "derived",
      group_key: "boost",
      formula_key: "map_minus_baro",
      input_keys: ["map_absolute", "barometer"],
    }),
    signal("desired_map", "Desired MAP", "Powertrain", "kPa abs", 103, { kind: "scalar" }, {
      confidence: "Candidate",
      provenance: ["GM Mode 22 $1542 live-probed candidate"],
      evidence: desiredMapEvidence,
      evidence_policy: "candidate",
    }),
    signal("barometer", "Barometer", "Powertrain", "kPa abs", 95, { kind: "scalar" }, {
      confidence: "Candidate",
      provenance: ["GM Mode 22 $1251 live-probed candidate"],
      evidence: barometerEvidence,
      evidence_policy: "candidate",
    }),
    signal("vgt_actual", "Actual", "Turbo", "%", 88.2, {
      kind: "pair",
      group_key: "turbo_vane_position",
      group_label: "VGT vane position",
      role: "actual",
    }, { confidence: "Community", provenance: ["ScanGauge LB7/LLY X-Gauge"] }),
    signal("vgt_desired", "Desired", "Turbo", "%", 88.2, {
      kind: "pair",
      group_key: "turbo_vane_position",
      group_label: "VGT vane position",
      role: "desired",
    }, { confidence: "Community", provenance: ["ScanGauge LB7/LLY X-Gauge"] }),
    signal("vgt_error", "Error", "Turbo", "%", 0, {
      kind: "pair",
      group_key: "turbo_vane_position",
      group_label: "VGT vane position",
      role: "error",
    }, { confidence: "LiveObserved", provenance: ["derived actual - desired"] }),
    signal("fuel_rail_actual", "Actual", "Fuel", "psi", 4260, {
      kind: "pair",
      group_key: "fuel_rail",
      group_label: "Fuel rail",
      role: "actual",
    }, { evidence: fuelRailActualEvidence, provenance: ["SAE PID 01 23"], preferred_over: "fuel_rail_actual_gm" }),
    signal("fuel_rail_desired", "Desired", "Fuel", "psi", 5510, {
      kind: "pair",
      group_key: "fuel_rail",
      group_label: "Fuel rail",
      role: "desired",
    }, { confidence: "Community", evidence: fuelRailDesiredEvidence, provenance: ["ScanGauge LB7/LLY X-Gauge"] }),
    signal("fuel_rail_delta", "Delta", "Fuel", "psi", -1250, {
      kind: "pair",
      group_key: "fuel_rail",
      group_label: "Fuel rail",
      role: "delta",
    }, { confidence: "LiveObserved", provenance: ["derived actual - desired"] }),
    signal("injector_balance_1", "Cylinder 1", "Fuel", "mm3", 0.3, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 1, row_label: "1" }, { confidence: "Community" }),
    signal("injector_balance_2", "Cylinder 2", "Fuel", "mm3", -0.3, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 2, row_label: "2" }, { confidence: "Community" }),
    signal("injector_balance_3", "Cylinder 3", "Fuel", "mm3", -1.3, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 3, row_label: "3" }, { confidence: "Community" }),
    signal("injector_balance_4", "Cylinder 4", "Fuel", "mm3", -0.4, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 4, row_label: "4" }, { confidence: "Community" }),
    signal("injector_balance_5", "Cylinder 5", "Fuel", "mm3", -0.3, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 5, row_label: "5" }, { confidence: "Community" }),
    signal("injector_balance_6", "Cylinder 6", "Fuel", "mm3", 0.2, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 6, row_label: "6" }, { confidence: "Community" }),
    signal("injector_balance_7", "Cylinder 7", "Fuel", "mm3", 1.0, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 7, row_label: "7" }, { confidence: "Community" }),
    signal("injector_balance_8", "Cylinder 8", "Fuel", "mm3", 0.5, { kind: "table_row", table_key: "injector_balance", table_label: "Injector balance", row_index: 8, row_label: "8" }, { confidence: "Community" }),
    signal("coolant_temp", "Coolant", "Other", "F", 170.6, { kind: "scalar" }),
    signal("intake_air_temp", "Intake Air", "Other", "F", 91.4, { kind: "scalar" }),
    signal("oil_temp", "Oil", "Other", "F", null, { kind: "scalar" }, { state: "waiting" }),
    signal("trans_temp", "Trans", "Other", "F", null, { kind: "scalar" }, { state: "waiting", confidence: "Community", module: "TCM" }),
    signal("ambient_temp", "Ambient", "Other", "F", null, { kind: "scalar" }, { state: "waiting" }),
    signal("battery_voltage", "Battery voltage", "Other", "V", 13.8, { kind: "scalar" }),
  ],
  diagnostic_services: [
    {
      key: "sae_dtc",
      label: "SAE DTC scan",
      module: "broadcast",
      state: "ok",
      detail: "Generic 03/07/0A scan is available.",
    },
    {
      key: "gm_class2_19",
      label: "GM Class 2 $19",
      module: "profile modules",
      state: "ok",
      detail: "Enhanced GM DTC decoder is available when the selected profile exposes module routes.",
    },
  ],
  alerts: [],
  dtcs: [],
  modules: [
    { module: "ECM", standard: "empty", gm_all: "empty", gm_active: "empty" },
    { module: "FICM", standard: "no data", gm_all: "no data", gm_active: "no data" },
    { module: "TCM", standard: "unsup", gm_all: "empty", gm_active: "empty" },
    { module: "IPC", standard: "probe", gm_all: "probe", gm_active: "probe" },
    { module: "EBCM", standard: "no data", gm_all: "empty", gm_active: "empty" },
    { module: "BCM", standard: "unsup", gm_all: "empty", gm_active: "empty" },
  ],
  active_tests_v2: [
    {
      key: "turbo_vane_control",
      label: "VGT vane control",
      safety_class: "stationary_idle_only",
      command_profile: "Locked",
      actionable: false,
      lock_reason: "Verified Tech2/EFILive/Snap-on Class 2 command bytes are required before execution.",
      supported_modes: ["TC Learn ON/OFF placeholder", "Manual vane percent placeholder"],
      safety_notes: [
        "Stationary-only; never while driving.",
        "Idle-only with warm coolant.",
        "Future enabled commands must timeout and release control automatically.",
        "Every attempt must be captured in the GM evidence stream.",
      ],
      preconditions: [
        {
          label: "Verified command profile",
          satisfied: false,
          detail: "No verified GM Class 2 actuator-control bytes are loaded.",
        },
        { label: "Stationary", satisfied: true, detail: "0.0 mph" },
        { label: "Idle speed", satisfied: true, detail: "685 rpm" },
        { label: "Warm coolant", satisfied: true, detail: "170.6 F" },
        { label: "Battery voltage", satisfied: true, detail: "13.8 V" },
        {
          label: "Park/Neutral and A/C off",
          satisfied: false,
          detail: "Not observable through current data; future enabled command must require operator confirmation.",
        },
      ],
      timeout_ms: 5_000,
      cancel_available: false,
      evidence_policy: "Always",
      last_result: null,
    },
  ],
  source_confidence: sourceConfidence,
};

export const genericObdSnapshot: MockDiagnosticSnapshot = {
  ...fallbackSnapshot,
  vehicle: "Generic OBD-II Vehicle",
  vin: "TESTGENERIC00001",
  protocol: "CAN 11-bit",
  connection: "browser mock / generic OBD-only",
  voltage: 12.6,
  rpm: 740,
  statuses: [
    { label: "DTCs", value: "0", state: "ok" },
    { label: "ECUs", value: "1", state: "ok" },
    { label: "MIL", value: "OFF", state: "ok" },
    { label: "Record", value: "armed", state: "warn" },
  ],
  modules: [{ module: "ECM", standard: "empty", gm_all: "unsupported", gm_active: "unsupported" }],
  capability_sections: [
    {
      id: "powertrain",
      category: "Powertrain",
      label: "Powertrain",
      signal_keys: ["generic_rpm", "generic_map", "generic_maf"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "emissions",
      category: "Emissions",
      label: "Emissions",
      signal_keys: ["generic_coolant", "generic_iat"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "diagnostics",
      category: "Diagnostics",
      label: "Diagnostics",
      signal_keys: [],
      active_test_keys: [],
      diagnostic_service_keys: ["sae_dtc"],
      visible: true,
    },
  ],
  signals: [
    signal("generic_rpm", "Engine RPM", "Powertrain", "rpm", 740, { kind: "scalar" }, { provenance: ["SAE PID 01 0C"] }),
    signal("generic_map", "Intake MAP", "Powertrain", "psi", 14.4, { kind: "scalar" }, { provenance: ["SAE PID 01 0B"] }),
    signal("generic_maf", "MAF", "Powertrain", "g/s", 4.7, { kind: "scalar" }, { provenance: ["SAE PID 01 10"] }),
    signal("generic_coolant", "Coolant", "Emissions", "F", 186.2, { kind: "scalar" }, { provenance: ["SAE PID 01 05"] }),
    signal("generic_iat", "Intake Air", "Emissions", "F", 82.4, { kind: "scalar" }, { provenance: ["SAE PID 01 0F"] }),
  ],
  active_tests_v2: [],
  diagnostic_services: [
    {
      key: "sae_dtc",
      label: "SAE DTC scan",
      module: "broadcast",
      state: "ok",
      detail: "Generic 03/07/0A scan only. No enhanced manufacturer profile is selected.",
    },
  ],
  source_confidence: [],
};

export const gasNoTurboSnapshot: MockDiagnosticSnapshot = {
  ...genericObdSnapshot,
  vehicle: "2020 Chevrolet Malibu 1.5L",
  vin: "TESTGASNOTURBO001",
  protocol: "CAN 11-bit",
  connection: "browser mock / gas no-turbo",
  voltage: 13.1,
  rpm: 702,
  speed_mph: 0,
  statuses: [
    { label: "DTCs", value: "0", state: "ok" },
    { label: "ECUs", value: "2", state: "ok" },
    { label: "MIL", value: "OFF", state: "ok" },
    { label: "Record", value: "armed", state: "warn" },
  ],
  modules: [
    { module: "ECM", standard: "empty", gm_all: "unsupported", gm_active: "unsupported" },
    { module: "TCM", standard: "empty", gm_all: "unsupported", gm_active: "unsupported" },
  ],
  capability_sections: [
    {
      id: "powertrain",
      category: "Powertrain",
      label: "Powertrain",
      signal_keys: ["gas_rpm", "gas_map", "gas_maf"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "emissions",
      category: "Emissions",
      label: "Emissions",
      signal_keys: ["gas_coolant", "gas_iat", "gas_stft", "gas_o2_voltage"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "diagnostics",
      category: "Diagnostics",
      label: "Diagnostics",
      signal_keys: [],
      active_test_keys: [],
      diagnostic_service_keys: ["sae_dtc"],
      visible: true,
    },
  ],
  signals: [
    signal("gas_rpm", "Engine RPM", "Powertrain", "rpm", 702, { kind: "scalar" }, { provenance: ["SAE PID 01 0C"] }),
    signal("gas_map", "Intake MAP", "Powertrain", "psi", 5.8, { kind: "scalar" }, { provenance: ["SAE PID 01 0B"] }),
    signal("gas_maf", "MAF", "Powertrain", "g/s", 3.1, { kind: "scalar" }, { provenance: ["SAE PID 01 10"] }),
    signal("gas_coolant", "Coolant", "Emissions", "F", 193.1, { kind: "scalar" }, { provenance: ["SAE PID 01 05"] }),
    signal("gas_iat", "Intake Air", "Emissions", "F", 79.0, { kind: "scalar" }, { provenance: ["SAE PID 01 0F"] }),
    signal("gas_stft", "Short-term fuel trim", "Emissions", "%", 1.6, { kind: "scalar" }, { provenance: ["SAE PID 01 06"] }),
    signal("gas_o2_voltage", "O2 sensor voltage", "Emissions", "V", 0.7, { kind: "scalar" }, { provenance: ["SAE PID 01 14"] }),
  ],
  active_tests_v2: [],
  source_confidence: [],
};

export const transmissionSnapshot: MockDiagnosticSnapshot = {
  ...genericObdSnapshot,
  vehicle: "Transmission-capable profile",
  vin: "TESTTRANS0000001",
  protocol: "CAN 29-bit",
  connection: "browser mock / transmission-capable",
  voltage: 13.9,
  rpm: 1560,
  speed_mph: 38,
  statuses: [
    { label: "DTCs", value: "0", state: "ok" },
    { label: "ECUs", value: "2", state: "ok" },
    { label: "MIL", value: "OFF", state: "ok" },
    { label: "Record", value: "armed", state: "warn" },
  ],
  modules: [
    { module: "ECM", standard: "empty", gm_all: "unsupported", gm_active: "unsupported" },
    { module: "TCM", standard: "empty", gm_all: "unsupported", gm_active: "unsupported" },
  ],
  capability_sections: [
    {
      id: "powertrain",
      category: "Powertrain",
      label: "Powertrain",
      signal_keys: ["trans_rpm", "trans_speed"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "transmission",
      category: "Transmission",
      label: "Transmission",
      signal_keys: ["trans_fluid_temp", "trans_commanded_gear", "trans_tcc_slip"],
      active_test_keys: [],
      diagnostic_service_keys: [],
      visible: true,
    },
    {
      id: "diagnostics",
      category: "Diagnostics",
      label: "Diagnostics",
      signal_keys: [],
      active_test_keys: [],
      diagnostic_service_keys: ["sae_dtc"],
      visible: true,
    },
  ],
  signals: [
    signal("trans_rpm", "Engine RPM", "Powertrain", "rpm", 1560, { kind: "scalar" }, { provenance: ["SAE PID 01 0C"] }),
    signal("trans_speed", "Vehicle speed", "Powertrain", "mph", 38, { kind: "scalar" }, { provenance: ["SAE PID 01 0D"] }),
    signal("trans_fluid_temp", "Transmission fluid temp", "Transmission", "F", 184.6, { kind: "scalar" }, {
      module: "TCM",
      provenance: ["profile signal"],
    }),
    signal("trans_commanded_gear", "Commanded gear", "Transmission", "", 4, { kind: "scalar" }, {
      module: "TCM",
      provenance: ["profile signal"],
    }),
    signal("trans_tcc_slip", "TCC slip", "Transmission", "rpm", 12, { kind: "scalar" }, {
      module: "TCM",
      provenance: ["profile signal"],
    }),
  ],
  active_tests_v2: [],
  source_confidence: [],
};
