import type { DiagnosticSnapshot } from "./types";

export const fallbackSnapshot: DiagnosticSnapshot = {
  vehicle: "2004 GMC Sierra",
  vin: "1GTHK29294E391526",
  protocol: "J1850 VPW",
  connection: "browser mock",
  voltage: 13.8,
  rpm: 685,
  speed_mph: 0,
  poll_ms: 250,
  units: "US",
  statuses: [
    { label: "DTCs", value: "0", state: "ok" },
    { label: "ECUs", value: "5", state: "ok" },
    { label: "MIL", value: "OFF", state: "ok" },
    { label: "Record", value: "armed", state: "warn" },
  ],
  alerts: [],
  dtcs: [],
  modules: [
    { module: "ECM", standard: "empty", gm_all: "empty", gm_active: "empty" },
    { module: "FICM", standard: "no data", gm_all: "no data", gm_active: "no data" },
    { module: "TCM", standard: "unsup", gm_all: "empty", gm_active: "empty" },
    { module: "IPC", standard: "probe", gm_all: "probe", gm_active: "probe" },
    { module: "EBCM", standard: "no data", gm_all: "empty", gm_active: "empty" },
    { module: "BCM", standard: "unsup", gm_all: "empty", gm_active: "empty" },
  ],
  cylinders: [
    { cylinder: 1, mm3: 0.3 },
    { cylinder: 2, mm3: -0.3 },
    { cylinder: 3, mm3: -1.3 },
    { cylinder: 4, mm3: -0.4 },
    { cylinder: 5, mm3: -0.3 },
    { cylinder: 6, mm3: 0.2 },
    { cylinder: 7, mm3: 1.0 },
    { cylinder: 8, mm3: 0.5 },
  ],
  vgt: { actual_pct: 88.2, desired_pct: 88.2, error_pct: 0.0 },
  fuel_rail: { actual_psi: 4260, desired_psi: 5510, delta_psi: -1250 },
  temperatures: {
    coolant_f: 170.6,
    intake_air_f: 91.4,
    oil_f: null,
    trans_f: null,
    ambient_f: null,
  },
  map_psi: 13.9,
  desired_map_psi: 14.9,
  barometric_psi: 13.8,
  boost_psi: 0,
  maf_g_s: 39.0,
  active_tests: {
    vgt_vane: {
      definition: {
        id: "vgt_vane_control",
        label: "VGT vane control",
        locked: true,
        lock_reason: "Verified Tech2/EFILive/Snap-on Class 2 command bytes are required before execution.",
        command_profile: "missing verified GM Class 2 actuator-control profile",
        supported_modes: ["TC Learn ON/OFF placeholder", "Manual vane percent placeholder"],
        safety_notes: [
          "Stationary-only; never while driving.",
          "Idle-only with warm coolant.",
          "Future enabled commands must timeout and release control automatically.",
          "Every attempt must be captured in the GM evidence stream.",
        ],
      },
      preconditions: [
        {
          label: "Verified command profile",
          satisfied: false,
          detail: "No verified GM Class 2 actuator-control bytes are loaded.",
        },
        { label: "Stationary", satisfied: true, detail: "0.0 mph" },
        { label: "Idle speed", satisfied: true, detail: "685 rpm" },
        { label: "Warm coolant", satisfied: true, detail: "170.6 F" },
        { label: "Battery voltage", satisfied: true, detail: "13.8 V" },
        {
          label: "Park/Neutral and A/C off",
          satisfied: false,
          detail: "Not observable through current data; future enabled command must require operator confirmation.",
        },
      ],
      last_result: null,
    },
  },
  source_confidence: [
    {
      key: "fuel_rail_actual",
      label: "Actual fuel rail SAE PID 01 23",
      module: "ECM",
      node: "broadcast",
      request: "01 23",
      source: "SAE standard PID",
      confidence: "standard; forced direct poll",
      status: "success",
      unit: "psi",
      value: 4260,
      response: null,
      notes: "Full-range gauge pressure; preferred over GM $22 163E X-Gauge scaling.",
    },
    {
      key: "fuel_rail_actual_gm",
      label: "Actual fuel rail GM $22 163E 01",
      module: "ECM/PCM",
      node: "0x10",
      request: "6C 10 F1 22 16 3E 01",
      source: "GM Mode 22",
      confidence: "ScanGauge published + live-observed; range-suspect",
      status: "success",
      unit: "psi",
      value: 4248,
      response: "1D4C",
      notes: "Standard PID 01 23 remains preferred for the displayed actual rail pressure.",
    },
    {
      key: "fuel_rail_desired",
      label: "Desired fuel rail GM $22 163D 01",
      module: "ECM/PCM",
      node: "0x10",
      request: "6C 10 F1 22 16 3D 01",
      source: "GM Mode 22",
      confidence: "ScanGauge published + live-observed; range-suspect",
      status: "success",
      unit: "psi",
      value: 5510,
      response: "2600",
      notes: "Display scaling is retained from current live/probe code until persisted bytes are cross-checked.",
    },
    {
      key: "desired_map",
      label: "Desired MAP GM $22 1542 01 candidate",
      module: "ECM/PCM",
      node: "0x10",
      request: "6C 10 F1 22 15 42 01",
      source: "GM Mode 22",
      confidence: "candidate; live behavior observed, validation pending",
      status: "success",
      unit: "kPa abs",
      value: 103,
      response: "67",
      notes: "Display as absolute pressure until cross-checked against a factory-equivalent tool.",
    },
    {
      key: "barometric_pressure_gm",
      label: "Barometer GM $22 1251 01 candidate",
      module: "ECM/PCM",
      node: "0x10",
      request: "6C 10 F1 22 12 51 01",
      source: "GM Mode 22",
      confidence: "candidate/live-observed; persisted byte evidence pending",
      status: "success",
      unit: "kPa abs",
      value: 95,
      response: "5F",
      notes: "Used when standard PID 01 33 is unavailable or stale.",
    },
  ],
};
